[workspace]
members = ["crates/sherwood"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2024"
description = "A static site generator with built-in development server"
license = "MIT"
repository = "https://github.com/thombruce/sherwood"
homepage = "https://github.com/thombruce/sherwood"
authors = ["Thom Bruce <thom@thombruce.com>"]

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"
publish = false
verify = true
