[site]
title = "Sherwood" # (required)
footer_text = "Â© 2026 Sherwood Static Site Generator." # (optional TODO: can we make copyright year dynamic?)

# [templates]
# page_template = "default.stpl"

# [css]
# entry_point = "main.css"
# minify = true
# source_maps = false
# remove_unused = false
# nesting = true

# [css.targets]
# chrome = "103"
# firefox = "115"
# safari = "15"
# edge = "127"

[breadcrumb]
max_items = 5
enabled = true
